### PR TITLE
Database Management Improvements

### PR DESCRIPTION
**Pull request by chrisfosterelli**
Relates to https://github.com/BCDevExchange/devex/issues/576

Tasks from the issue were the following: 
* Update the existing database migration tools to be available as a configurable service in OpenShift
* Implement an automatic scheduled backup for the MongoDB database to replace the current manual backup procedure
* Fully document the new tools and brief the Developer’s Exchange team on their design and use

This PR introduces a backup container that keeps 7 days of automated nightly backups, and also converts the scrubber script into a configurable web service integrated with the BCDevEx OpenShift deployment. This allows automated downloading of scrubbed database exports, and importing of those exports into other environments through a simple web request using curl.

It also converts the devex utilities repository to be based on openshift templates, making deployment and integration with the main BCDevEx application more manageable. Documentation for using the two independent containers and deploying them in unison through the openshift template has been included.

The original scrubber ended up requiring more maintenance work than was originally anticipated, so the majority of it has been rewritten to facilitate improved long term integration and better automation opportunities.

### CODE REVIEW

**Comment by chrisfosterelli** [comment]
This also updates the scrubber to use async/await in order to reduce the lines of code required and make the logic more approachable, and updates the scrubber to handle scrubbing the new collections in the BCDevEx database that have been added since the script was originally written.

**Comment by chrisfosterelli** [comment]
To help facilitate review, here are the key pieces of documentation:
 https://github.com/BCDevExchange/devexUtils/blob/91a38d9b2be336587fbc4d65a7217099bf43ea06/openshift/README.md
https://github.com/BCDevExchange/devexUtils/blob/91a38d9b2be336587fbc4d65a7217099bf43ea06/scrubber/README.md
https://github.com/BCDevExchange/devexUtils/blob/91a38d9b2be336587fbc4d65a7217099bf43ea06/backup/README.md

**Comment by sutherlanda** [comment]
Thanks again @chrisfosterelli for your work on this.  This is a great set of improvements!

**Comment by chrisfosterelli** [comment]
@sutherlanda No problem, glad this works well for you!

**Pull request merged**
