### PR TITLE
DB Scrubber Node.js utility update

### PR DESCRIPTION
**Pull request by amanji**
feat(scrubber): Updates Node.js MongoDB scrubber utility application

Adds exporter and importer modules that use mongodump and mongorestore, respectively.
Updates code to ES6 syntax.
Expands ENV parameter requirements to account for changes in the updated scrubbing workflow.
Updates README with new instructions.

### CODE REVIEW

**Comment by ccoldwell** [comment]
2 things
1. Not sure if the version of node we are using in the project supports es6 syntax, I remember trying it at one point and having issues.
2. For emails we wanted to generate gmail emails that will all end up at the same inbox - there is a pattern to follow for this (can't remember exactly but something like testing.devex.1@gmail.com, testing.devex.2@gamil.com, etc). this would allow us to perform end-to-end testing including receipt of notification emails

**Comment by amanji** [comment]
1. From what I spoke to with @agehlers. The exporter/importer container environment (which this code would be housed in) will have Node.js 4+ so we should be fine with es6 syntax. I also tested in the containers she provided for development and they worked ok (I guess that's the advantage of having these encapsulated environments).

2. I can update the scrubber so that instead of simply removing the emails, it replaces them with whichever pattern is suitable for notification testing. At the time I wasn't sure which approach we wanted to go with so I just cleaned them from the data but it is easy to replace them instead.

**Comment by scchapma** [comment]
1.  Since @amanji reviewed this issue with @agehlers, let's leave it the way it is.  If @agehlers runs into difficulty when testing in Production, we can modify that.

2.  @ccoldwell - where do we find the pattern for replacing the emails?  Who do we need to talk to about that?

**Comment by scchapma** [comment]
@Akiff - @ccoldwell will give you express instructions on what to do.  What we want to do is to create a devex Gmail account that we can use to test the Notifications module.

**Comment by scchapma** [comment]
@amanji  - @ccoldwell will give you express instructions on what to do. What we want to do is to create a devex Gmail account that we can use to test the Notifications module.

**Comment by scchapma** [comment]
Let's merge this now, as @agehlers is ready to set up the Staging environment for the app and requires @amanji's utilities.  After this PR goes through, we will talk about setting up the Gmail notifications properly.

**Pull request merged**
